### ISSUE TITLE
Can't add private event

### ISSUE THREAD

**Issue by PhotoKevin** [damiant/dust#106]
Android. Tried both 11 and 13 on two different phones and a tablet
Dust version released on July 25, 2024 (Sorry, I don't see a version number).

For Burning Man, I tried to add a private event. I can put in the Title, Address, and Notes, but not the Time. And I can't save it without entering that field.

**Comment by damiant** [comment]
Thanks so much for the bug report. I'm looking into this now, it seems to be limited to Android for some reason...

**Comment by damiant** [comment]
I've fixed this issue ([PR](https://github.com/damiant/dust/pull/107)) and submitted the fix to the Play Store.

Interestingly it seems to be a bug in ion-datetime-button which I'll report to Ionic. For the moment I've got a workaround of showing the calendar and time for the private event.

Thanks for the bug report!

**Comment by PhotoKevin** [comment]
It works on my Android 11 phone, but not quite on my Android 13 tablet.  Here's the initial add screen. I can specify a time but not the day. If I save it though, and come back I get the calendar view and can fix the day.


![Screenshot_2024-07-27-19-37-40-842](https://github.com/user-attachments/assets/4d0908b3-5167-481d-b353-843fef6b2add)

**Comment by PhotoKevin** [comment]
Other things with the same page.
1) Times are entered with the users local time, not as BRC local time. i.e. I have an event that FB says is 9:30 EDT. I mentally translated that to 6:30 PDT (aka BRC time) and entered 6:30. The event then showed as 3:30. Not sure there's a happy answer, but I suspect most people would be told "Meet at the man noon Wed" and want to enter the time as noon, not as whatever their local time is. I'm working off the idea that this kind of planning is occurring before they get to the event. Once they're there, the issues will go away.

2) You can't change the location. 

3) Getting into the event to edit it is problematic. I'm not really sure if I should tap, or long press. I try one, then the other, then the first, etc. After a few tried I get in but I'm not sure what did it.

**Comment by damiant** [comment]
I reworked that screen again which seemed to show or hide the date and time almost randomly. Its submitted to Google again.

I also tested out the notification system which does take into account the time zone of the device - changing the notification time to the local time so that the notification appears correctly. I found that the events getting imported in from Burning Man were in PST - so they have been changed to timezoneless which means that dust won't alter their time if the device is not in PST.

**Comment by PhotoKevin** [comment]
The date/time entry seems good now. It is still shifting the time based on zone, but I can cope with that.
Changing the address works now too.

I don't know if you did anything for getting into the edit screen, but it's working nicely now.

Thanks for the fast response.

**Comment by damiant** [comment]
Hey Kevin, I'm wondering how you are testing the time based on zone. If you are entering a private event for Burning Man at say 9am PST, but you are located in New York then the notification will be setup to be triggered at 12pm EST. It will be shown in the app as 9am though. So, I'm wondering how you might be seeing shifting based on timezone?

**Comment by PhotoKevin** [comment]
Scenario: A friend says "Meet at Center Camp Noon Tuesday". I'm in EDT. They're in Berlin. But we both know Noon in this case means Noon in BRC because that's where we'll be.

I hit the plus.
Enter title: "Meet Friend"
Address: 6:00 & Center Camp
Time: 12:00 PM.
Hit save.
The list of private events shows it as being at 9:00am
I don't know about when any notification will trigger.

**Comment by damiant** [comment]
Thanks for explaining the scenario - I didn't notice that the time was displayed for the wrong timezone. This should now be fixed in v2.36 which I just sent over to the play and app stores.
